import { AlertTriangle, Shield, UserCheck, Lock, FileWarning } from "lucide-react";
import Navbar from "../components/Navbar.jsx";
import Footer from "../components/Footer.jsx";

const Disclaimer = () => {
  const sections = [
    {
      icon: AlertTriangle,
      title: "Not a Diagnostic Tool",
      content: "MedInsight AI is a clinical decision support system designed to assist in the interpretation of medical reports. It does NOT provide medical diagnoses, treatment recommendations, or replace the judgment of qualified healthcare professionals. The outputs generated by this system should be used for informational purposes only.",
    },
    {
      icon: UserCheck,
      title: "Not a Replacement for Doctors",
      content: "This system is intended to supplement, not replace, the expertise of licensed healthcare providers. All medical decisions should be made in consultation with qualified physicians, specialists, or other healthcare professionals who can consider your complete medical history and current condition.",
    },
    {
      icon: Lock,
      title: "Data Privacy & Security",
      content: "We take data privacy seriously. Medical reports uploaded to our system are processed using secure protocols. We use de-identified data processing where possible and do not permanently store personal health information beyond the analysis session. However, users should exercise caution when uploading sensitive medical information.",
    },
    {
      icon: Shield,
      title: "Clinical Decision Support",
      content: "This system is designed as a clinical decision support tool to help healthcare professionals and educated patients better understand medical report findings. The AI analysis provides structured summaries, reference comparisons, and potential areas of concern that should be validated by qualified medical professionals.",
    },
    {
      icon: FileWarning,
      title: "Limitations of AI Analysis",
      content: "AI-based analysis has inherent limitations. Accuracy depends on the quality of uploaded documents, and the system may not capture all nuances that a trained medical professional would identify. False positives and false negatives are possible. Always verify findings with appropriate clinical testing and professional consultation.",
    },
  ];

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />

      <main className="flex-1 py-12 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <div className="p-4 bg-status-warning/10 rounded-full w-fit mx-auto mb-4">
              <AlertTriangle className="h-10 w-10 text-status-warning" />
            </div>
            <h1 className="text-2xl md:text-3xl font-bold text-foreground mb-4">
              Disclaimer & Ethics
            </h1>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Please read this important information before using MedInsight AI
            </p>
          </div>

          <div className="space-y-6">
            {sections.map((section, index) => (
              <div key={index} className="medical-card">
                <div className="flex items-start gap-4">
                  <div className="p-2 bg-primary/10 rounded-lg flex-shrink-0">
                    <section.icon className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <h2 className="text-lg font-semibold text-foreground mb-2">
                      {section.title}
                    </h2>
                    <p className="text-muted-foreground leading-relaxed">
                      {section.content}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Acceptance Statement */}
          <div className="mt-12 p-6 bg-secondary rounded-lg border border-border">
            <h3 className="font-semibold text-foreground mb-3">By Using This System, You Acknowledge:</h3>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                <span>You have read and understood this disclaimer</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                <span>You understand this is not a substitute for professional medical advice</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                <span>You will consult healthcare professionals for medical decisions</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-primary">•</span>
                <span>You accept the limitations of AI-based analysis</span>
              </li>
            </ul>
          </div>

          {/* Contact */}
          <div className="mt-8 text-center">
            <p className="text-sm text-muted-foreground">
              For questions or concerns about this system, please contact your healthcare provider 
              or the system administrator.
            </p>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Disclaimer;
