// import { AlertTriangle, Shield, UserCheck, Lock, FileWarning } from "lucide-react";
// import Navbar from "../components/Navbar.jsx";
// import Footer from "../components/Footer.jsx";

// const Disclaimer = () => {
//   const sections = [
//     {
//       icon: AlertTriangle,
//       title: "Not a Diagnostic Tool",
//       content: "MedInsight AI is a clinical decision support system designed to assist in the interpretation of medical reports. It does NOT provide medical diagnoses, treatment recommendations, or replace the judgment of qualified healthcare professionals. The outputs generated by this system should be used for informational purposes only.",
//     },
//     {
//       icon: UserCheck,
//       title: "Not a Replacement for Doctors",
//       content: "This system is intended to supplement, not replace, the expertise of licensed healthcare providers. All medical decisions should be made in consultation with qualified physicians, specialists, or other healthcare professionals who can consider your complete medical history and current condition.",
//     },
//     {
//       icon: Lock,
//       title: "Data Privacy & Security",
//       content: "We take data privacy seriously. Medical reports uploaded to our system are processed using secure protocols. We use de-identified data processing where possible and do not permanently store personal health information beyond the analysis session. However, users should exercise caution when uploading sensitive medical information.",
//     },
//     {
//       icon: Shield,
//       title: "Clinical Decision Support",
//       content: "This system is designed as a clinical decision support tool to help healthcare professionals and educated patients better understand medical report findings. The AI analysis provides structured summaries, reference comparisons, and potential areas of concern that should be validated by qualified medical professionals.",
//     },
//     {
//       icon: FileWarning,
//       title: "Limitations of AI Analysis",
//       content: "AI-based analysis has inherent limitations. Accuracy depends on the quality of uploaded documents, and the system may not capture all nuances that a trained medical professional would identify. False positives and false negatives are possible. Always verify findings with appropriate clinical testing and professional consultation.",
//     },
//   ];

//   return (
//     <div className="min-h-screen flex flex-col bg-background">
//       <Navbar />

//       <main className="flex-1 py-12 px-4">
//         <div className="max-w-4xl mx-auto">
//           <div className="text-center mb-12">
//             <div className="p-4 bg-status-warning/10 rounded-full w-fit mx-auto mb-4">
//               <AlertTriangle className="h-10 w-10 text-status-warning" />
//             </div>
//             <h1 className="text-2xl md:text-3xl font-bold text-foreground mb-4">
//               Disclaimer & Ethics
//             </h1>
//             <p className="text-muted-foreground max-w-2xl mx-auto">
//               Please read this important information before using MedInsight AI
//             </p>
//           </div>

//           <div className="space-y-6">
//             {sections.map((section, index) => (
//               <div key={index} className="medical-card">
//                 <div className="flex items-start gap-4">
//                   <div className="p-2 bg-primary/10 rounded-lg flex-shrink-0">
//                     <section.icon className="h-6 w-6 text-primary" />
//                   </div>
//                   <div>
//                     <h2 className="text-lg font-semibold text-foreground mb-2">
//                       {section.title}
//                     </h2>
//                     <p className="text-muted-foreground leading-relaxed">
//                       {section.content}
//                     </p>
//                   </div>
//                 </div>
//               </div>
//             ))}
//           </div>

//           {/* Acceptance Statement */}
//           <div className="mt-12 p-6 bg-secondary rounded-lg border border-border">
//             <h3 className="font-semibold text-foreground mb-3">By Using This System, You Acknowledge:</h3>
//             <ul className="space-y-2 text-sm text-muted-foreground">
//               <li className="flex items-start gap-2">
//                 <span className="text-primary">•</span>
//                 <span>You have read and understood this disclaimer</span>
//               </li>
//               <li className="flex items-start gap-2">
//                 <span className="text-primary">•</span>
//                 <span>You understand this is not a substitute for professional medical advice</span>
//               </li>
//               <li className="flex items-start gap-2">
//                 <span className="text-primary">•</span>
//                 <span>You will consult healthcare professionals for medical decisions</span>
//               </li>
//               <li className="flex items-start gap-2">
//                 <span className="text-primary">•</span>
//                 <span>You accept the limitations of AI-based analysis</span>
//               </li>
//             </ul>
//           </div>

//           {/* Contact */}
//           <div className="mt-8 text-center">
//             <p className="text-sm text-muted-foreground">
//               For questions or concerns about this system, please contact your healthcare provider 
//               or the system administrator.
//             </p>
//           </div>
//         </div>
//       </main>

//       <Footer />
//     </div>
//   );
// };

// export default Disclaimer;





















import { AlertTriangle, Shield, UserCheck, Lock, FileWarning } from "lucide-react";
import Navbar from "../components/Navbar.jsx";
import Footer from "../components/Footer.jsx";

const Disclaimer = () => {
  const sections = [
    { icon: AlertTriangle, title: "Not a Diagnostic Tool", content: "MedInsight AI is a clinical decision support system designed to assist in the interpretation of medical reports. It does NOT provide medical diagnoses, treatment recommendations, or replace the judgment of qualified healthcare professionals. The outputs generated by this system should be used for informational purposes only." },
    { icon: UserCheck, title: "Not a Replacement for Doctors", content: "This system is intended to supplement, not replace, the expertise of licensed healthcare providers. All medical decisions should be made in consultation with qualified physicians, specialists, or other healthcare professionals who can consider your complete medical history and current condition." },
    { icon: Lock, title: "Data Privacy & Security", content: "We take data privacy seriously. Medical reports uploaded to our system are processed using secure protocols. We use de-identified data processing where possible and do not permanently store personal health information beyond the analysis session. However, users should exercise caution when uploading sensitive medical information." },
    { icon: Shield, title: "Clinical Decision Support", content: "This system is designed as a clinical decision support tool to help healthcare professionals and educated patients better understand medical report findings. The AI analysis provides structured summaries, reference comparisons, and potential areas of concern that should be validated by qualified medical professionals." },
    { icon: FileWarning, title: "Limitations of AI Analysis", content: "AI-based analysis has inherent limitations. Accuracy depends on the quality of uploaded documents, and the system may not capture all nuances that a trained medical professional would identify. False positives and false negatives are possible. Always verify findings with appropriate clinical testing and professional consultation." },
  ];

  const iconColors = ["text-amber-500", "text-blue-500", "text-violet-500", "text-primary", "text-rose-500"];
  const bgColors = ["bg-amber-50", "bg-blue-50", "bg-violet-50", "bg-primary/10", "bg-rose-50"];

  return (
    <div className="min-h-screen flex flex-col" style={{background: "linear-gradient(135deg, #dbeafe 0%, #eff6ff 40%, #e0f2fe 80%, #f0f9ff 100%)"}}>
      <Navbar />
      <main className="flex-1 py-12 px-4">
        <div className="max-w-4xl mx-auto">

          <div className="text-center mb-10">
            <div className="inline-flex p-3 bg-amber-50 border border-amber-200 rounded-2xl mb-4">
              <AlertTriangle className="h-8 w-8 text-amber-500" />
            </div>
            <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-3 py-1 rounded-full text-xs font-semibold mb-3 border border-primary/20 ml-0 block">
            </div>
            <h1 className="text-3xl font-bold text-slate-900 mb-3">Disclaimer & Ethics</h1>
            <p className="text-slate-500 max-w-2xl mx-auto text-sm">Please read this important information before using MedInsight AI</p>
          </div>

          <div className="space-y-3 mb-8">
            {sections.map((section, index) => (
              <div key={index} className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5 flex items-start gap-4 hover:shadow-md transition-all">
                <div className={`p-2.5 ${bgColors[index]} rounded-xl shrink-0`}>
                  <section.icon className={`h-5 w-5 ${iconColors[index]}`} />
                </div>
                <div>
                  <h2 className="font-semibold text-slate-800 mb-1.5">{section.title}</h2>
                  <p className="text-sm text-slate-500 leading-relaxed">{section.content}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 mb-6">
            <h3 className="font-semibold text-slate-800 mb-4 flex items-center gap-2">
              <Shield className="h-4 w-4 text-primary" />
              By Using This System, You Acknowledge:
            </h3>
            <div className="space-y-2.5">
              {[
                "You have read and understood this disclaimer",
                "You understand this is not a substitute for professional medical advice",
                "You will consult healthcare professionals for medical decisions",
                "You accept the limitations of AI-based analysis",
              ].map((item, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                  <div className="w-5 h-5 bg-primary/10 rounded-full flex items-center justify-center shrink-0 mt-0.5">
                    <div className="w-1.5 h-1.5 bg-primary rounded-full" />
                  </div>
                  <span className="text-sm text-slate-600">{item}</span>
                </div>
              ))}
            </div>
          </div>

          <p className="text-center text-sm text-slate-400">
            For questions or concerns about this system, please contact your healthcare provider or the system administrator.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Disclaimer;
