import { AlertTriangle } from "lucide-react";

const DisclaimerBox = ({ variant = "default" }) => {
  const styles = {
    default: "bg-secondary border-border",
    warning: "bg-status-warning/10 border-status-warning/30",
  };

  return (
    <div className={`rounded-lg border p-4 ${styles[variant]}`}>
      <div className="flex items-start gap-3">
        <AlertTriangle className="h-5 w-5 text-status-warning flex-shrink-0 mt-0.5" />
        <div>
          <h4 className="font-medium text-foreground text-sm">Important Disclaimer</h4>
          <p className="text-sm text-muted-foreground mt-1">
            This output is generated by an AI-assisted system and should not be considered a medical diagnosis. 
            Always consult with a qualified healthcare professional for medical advice.
          </p>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerBox;
